version: '3'
services:

  de_development:
    image: jgsoftwares/graalce11
    container_name: de_development
    ports:
      - "217.160.255.254:22:22"
    networks:
      192.168.178.0:
        ipv4_address: 192.168.178.2

    build:
      context: ./
      dockerfile: Dockerfilesshserver


    environment:
      - TZ=Europe/Berlin
    dns:
      - 208.67.222.222
      - 208.67.220.220
      - 208.67.220.222
      - 208.67.222.220

networks:
  192.168.178.0:
    external: true


